baseURL: "https://chiragbellara.github.io"
title: Chirag Bellara
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - name: Projects
      url: projects/
      weight: 3
    - name: Papers
      url: papers/
      weight: 4
    - name: Experience
      url: experience/
      weight: 2
    - name: Blog
      url: data/
      weight: 5

params:
  description: "This website hosts Chirag Bellara's profile, projects, experience, papers, blogs and contact information."
  author: Chirag Bellara
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["experience", "projects", "papers"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Chirag Bellara
    subtitle: "I love building things that live on the web — clean, simple tools and experiences that people actually enjoy using. Over the past few years, I’ve brought all kinds of ideas to life, from interactive websites to behind-the-scenes systems that keep everything running smoothly. I’m also really into exploring how machines can learn and help us make better decisions — it’s one of the things that keeps me curious and excited about what I do. When I’m not working, I’m usually tinkering with a new project, picking up a random skill, or just chasing down whatever’s caught my interest that week."
    imageUrl: "color_picture.jpg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Experience
        url: experience/
      - name: Projects
        url: projects/
      - name: Papers
        url: papers/
      # - name: Data
      #   url: data/
      - name: Tags
        url: tags/
      - name: Timeline
        url: archive/
      - name: Blog
        url: data/

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: Email
      url: mailto:chiragbellara7@gmail.com
    - name: LinkedIn
      url: https://www.linkedin.com/in/chiragbellara/
    - name: GitHub
      url: https://github.com/ChiragBellara
    - name: Medium
      url: https://medium.com/@ChiragBellara

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Chirag Bellara"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
